#!/bin/sh

case "${1}" in
   start)
      start-stop-daemon --start --background --exec /usr/local/bin/autocapture
      ;;

   stop)
      start-stop-daemon --stop --background --exec /usr/local/bin/autocapture
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)

      echo "Usage: ${0} {start|stop|restart}"
      exit 1

      ;;
esac
